import React from "react";
import { Link } from "react-router-dom";
import { ArrowLeft } from "lucide-react";

function Container({ children, className = "" }) {
  return (
    <div className={`mx-auto w-full max-w-4xl px-5 sm:px-8 ${className}`}>
      {children}
    </div>
  );
}

export default function Terms() {
  return (
    <div className="min-h-screen bg-black text-white">
      {/* Header */}
      <div className="border-b border-white/10 bg-black/80 backdrop-blur sticky top-0 z-50">
        <Container className="py-4">
          <div className="flex items-center justify-between">
            <Link to="/" className="flex items-center gap-2 text-white/60 hover:text-white transition text-sm">
              <ArrowLeft className="h-4 w-4" />
              Back to HridAI
            </Link>
            <Link to="/privacy" className="text-sm text-white/60 hover:text-white transition">
              Privacy Policy
            </Link>
          </div>
        </Container>
      </div>

      <Container className="py-12 sm:py-16">
        {/* Title */}
        <h1 className="text-3xl font-bold tracking-tight sm:text-4xl">Terms of Service</h1>
        <div className="mt-4 flex flex-wrap gap-4 text-sm text-white/40">
          <span>Effective Date: March 26, 2026</span>
          <span>Last Updated: March 26, 2026</span>
        </div>
        <div className="mt-2 text-sm text-white/40">
          Company: uFactorial (ufactorial.com) &middot; Product: HridAI
        </div>

        <hr className="my-10 border-white/10" />

        {/* Agreement Overview */}
        <section>
          <h2 className="text-2xl font-bold">Agreement Overview</h2>
          <p className="mt-4 text-white/60 leading-7">
            These Terms of Service ("Terms") govern your use of HridAI, a personal intelligence application operated
            by uFactorial ("we," "us," "our"). By creating an account or using HridAI, you agree to these Terms.
          </p>
          <p className="mt-4 text-white/60 leading-7">
            If you don't agree, don't use HridAI. (We mean that respectfully — we just want to be clear.)
          </p>
        </section>

        <hr className="my-10 border-white/10" />

        {/* 1. What HridAI Is */}
        <section>
          <h2 className="text-2xl font-bold">1. What HridAI Is</h2>
          <p className="mt-4 text-white/60 leading-7">
            HridAI is an AI-powered personal intelligence tool. You talk to it, and it learns about you — your goals,
            relationships, interests, concerns, and the threads of your life. It builds a structured knowledge graph
            that helps you reflect, remember, and organize your thinking.
          </p>

          <p className="mt-6 font-semibold text-white">HridAI is:</p>
          <ul className="mt-3 space-y-2 text-white/60 leading-7">
            <li className="flex gap-3"><span className="text-emerald-400">+</span> A personal tool for self-reflection and organization</li>
            <li className="flex gap-3"><span className="text-emerald-400">+</span> An AI that remembers your context across conversations</li>
            <li className="flex gap-3"><span className="text-emerald-400">+</span> A way to visualize and explore what you've shared</li>
          </ul>

          <p className="mt-6 font-semibold text-white">HridAI is <strong>not</strong>:</p>
          <ul className="mt-3 space-y-2 text-white/60 leading-7">
            <li className="flex gap-3"><span className="text-red-400">✕</span> A therapist, counselor, or mental health provider</li>
            <li className="flex gap-3"><span className="text-red-400">✕</span> A doctor or medical advisor</li>
            <li className="flex gap-3"><span className="text-red-400">✕</span> A lawyer or legal advisor</li>
            <li className="flex gap-3"><span className="text-red-400">✕</span> A financial advisor or planner</li>
            <li className="flex gap-3"><span className="text-red-400">✕</span> A substitute for professional advice of any kind</li>
          </ul>

          <div className="mt-6 rounded-xl border border-amber-400/30 bg-amber-400/5 p-5">
            <p className="text-white/70 leading-7">
              <strong className="text-amber-400">Important:</strong> HridAI's responses are generated by AI. They may
              be helpful, insightful, or useful for self-reflection — but they are not professional advice. If you need
              professional help (medical, legal, financial, psychological), please consult a qualified professional.
            </p>
          </div>
        </section>

        <hr className="my-10 border-white/10" />

        {/* 2. Account Requirements */}
        <section>
          <h2 className="text-2xl font-bold">2. Account Requirements</h2>
          <p className="mt-4 text-white/60 leading-7">To use HridAI, you must:</p>
          <ul className="mt-3 space-y-2 text-white/60 leading-7">
            <li className="flex gap-3"><span className="text-emerald-400">•</span> <strong className="text-white">Be at least 18 years old.</strong> HridAI is not designed for minors.</li>
            <li className="flex gap-3"><span className="text-emerald-400">•</span> <strong className="text-white">Provide a valid email address</strong> for account creation.</li>
            <li className="flex gap-3"><span className="text-emerald-400">•</span> <strong className="text-white">Create a secure password</strong> and keep it confidential.</li>
            <li className="flex gap-3"><span className="text-emerald-400">•</span> <strong className="text-white">Provide accurate information.</strong> Don't create accounts with false identities.</li>
          </ul>
          <p className="mt-4 text-white/60 leading-7">
            You are responsible for all activity under your account. If you suspect unauthorized access, contact us
            immediately at{" "}
            <a href="mailto:support@ufactorial.com" className="text-emerald-400 hover:underline">support@ufactorial.com</a>.
          </p>
        </section>

        <hr className="my-10 border-white/10" />

        {/* 3. Subscription Tiers and Payment */}
        <section>
          <h2 className="text-2xl font-bold">3. Subscription Tiers and Payment</h2>

          <h3 className="mt-8 text-xl font-semibold">3.1 Free Tier</h3>
          <ul className="mt-3 space-y-2 text-white/60 leading-7">
            <li className="flex gap-3"><span className="text-emerald-400">•</span> <strong className="text-white">5 conversations per day</strong></li>
            <li className="flex gap-3"><span className="text-emerald-400">•</span> <strong className="text-white">14-day memory depth</strong> — HridAI actively processes your last 14 days of conversation</li>
            <li className="flex gap-3"><span className="text-emerald-400">•</span> Access to all views and features within these limits</li>
          </ul>
          <p className="mt-3 text-white/60 leading-7">No payment required. No credit card required to start.</p>

          <h3 className="mt-8 text-xl font-semibold">3.2 Premium Tier</h3>
          <ul className="mt-3 space-y-2 text-white/60 leading-7">
            <li className="flex gap-3"><span className="text-emerald-400">•</span> <strong className="text-white">$20/month (USD)</strong></li>
            <li className="flex gap-3"><span className="text-emerald-400">•</span> <strong className="text-white">Unlimited conversations</strong></li>
            <li className="flex gap-3"><span className="text-emerald-400">•</span> <strong className="text-white">Full memory depth</strong> — HridAI retains and processes your entire conversation history</li>
            <li className="flex gap-3"><span className="text-emerald-400">•</span> Access to all current and future premium features</li>
          </ul>

          <h3 className="mt-8 text-xl font-semibold">3.3 Billing</h3>
          <ul className="mt-3 space-y-2 text-white/60 leading-7">
            <li className="flex gap-3"><span className="text-emerald-400">•</span> Premium subscriptions are billed <strong className="text-white">monthly</strong> via Stripe.</li>
            <li className="flex gap-3"><span className="text-emerald-400">•</span> Your subscription renews automatically unless you cancel.</li>
            <li className="flex gap-3"><span className="text-emerald-400">•</span> You can cancel at any time. Cancellation takes effect at the end of your current billing period — you keep Premium access until then.</li>
            <li className="flex gap-3"><span className="text-emerald-400">•</span> <strong className="text-white">No refunds</strong> for partial months. If you cancel mid-cycle, you retain access through the end of that billing period.</li>
            <li className="flex gap-3"><span className="text-emerald-400">•</span> We may change pricing with <strong className="text-white">30 days' notice</strong> via email. Price changes apply at your next renewal — they never affect your current billing period.</li>
          </ul>

          <h3 className="mt-8 text-xl font-semibold">3.4 Free Trial and Promotions</h3>
          <p className="mt-4 text-white/60 leading-7">
            We may offer free trials or promotional pricing from time to time. Trial terms will be communicated at
            signup. If a trial converts to a paid subscription, you will be notified before the first charge.
          </p>
        </section>

        <hr className="my-10 border-white/10" />

        {/* 4. Your Data — You Own It */}
        <section>
          <h2 className="text-2xl font-bold">4. Your Data — You Own It</h2>
          <p className="mt-4 text-white/60 leading-7">
            This is fundamental to HridAI, so we want to be explicit:
          </p>
          <ul className="mt-3 space-y-3 text-white/60 leading-7">
            <li className="flex gap-3">
              <span className="text-emerald-400 font-bold">•</span>
              <span><strong className="text-white">You own your data.</strong> The conversations you have, the entities extracted, the knowledge graph built from your interactions — that's yours.</span>
            </li>
            <li className="flex gap-3">
              <span className="text-emerald-400 font-bold">•</span>
              <span><strong className="text-white">You can see all of it.</strong> HridAI's Vault UI shows you everything we know about you. That transparency is a core feature, not an afterthought.</span>
            </li>
            <li className="flex gap-3">
              <span className="text-emerald-400 font-bold">•</span>
              <span><strong className="text-white">You can export all of it.</strong> At any time, you can export your complete data set in JSON format. This includes: conversations, entities, relationships, topics, episodes, self-graph entries, todos, and lists.</span>
            </li>
            <li className="flex gap-3">
              <span className="text-emerald-400 font-bold">•</span>
              <span><strong className="text-white">You can delete all of it.</strong> You can delete specific items or your entire account. Account deletion permanently removes all your data within 30 days.</span>
            </li>
          </ul>
          <p className="mt-4 text-white/60 leading-7">
            We do not claim ownership of your data. We do not use your data to train AI models. We do not sell your data.
          </p>
          <p className="mt-4 text-white/60 leading-7">
            For full details, see our <Link to="/privacy" className="text-emerald-400 hover:underline">Privacy Policy</Link>.
          </p>
        </section>

        <hr className="my-10 border-white/10" />

        {/* 5. Our Intellectual Property */}
        <section>
          <h2 className="text-2xl font-bold">5. Our Intellectual Property</h2>
          <p className="mt-4 text-white/60 leading-7">While you own your data, we own HridAI:</p>
          <ul className="mt-3 space-y-2 text-white/60 leading-7">
            <li className="flex gap-3"><span className="text-emerald-400">•</span> The HridAI application, its code, design, and architecture are the intellectual property of uFactorial.</li>
            <li className="flex gap-3"><span className="text-emerald-400">•</span> The HridAI name, logo, and branding are trademarks of uFactorial.</li>
            <li className="flex gap-3"><span className="text-emerald-400">•</span> You may not copy, modify, distribute, or reverse-engineer any part of the HridAI application.</li>
          </ul>
          <p className="mt-4 text-white/60 leading-7">Your license to use HridAI is:</p>
          <ul className="mt-3 space-y-2 text-white/60 leading-7">
            <li className="flex gap-3"><span className="text-emerald-400">•</span> <strong className="text-white">Non-exclusive</strong> — others can use it too.</li>
            <li className="flex gap-3"><span className="text-emerald-400">•</span> <strong className="text-white">Non-transferable</strong> — your account is yours alone.</li>
            <li className="flex gap-3"><span className="text-emerald-400">•</span> <strong className="text-white">Revocable</strong> — we can terminate access per Section 8.</li>
            <li className="flex gap-3"><span className="text-emerald-400">•</span> <strong className="text-white">Limited</strong> — to personal use as described in these Terms.</li>
          </ul>
        </section>

        <hr className="my-10 border-white/10" />

        {/* 6. Acceptable Use */}
        <section>
          <h2 className="text-2xl font-bold">6. Acceptable Use</h2>
          <p className="mt-4 text-white/60 leading-7">
            You agree to use HridAI only for <strong className="text-white">personal, non-commercial purposes</strong>.
            Specifically, you will not:
          </p>
          <ul className="mt-3 space-y-2 text-white/60 leading-7">
            <li className="flex gap-3"><span className="text-red-400">✕</span> <strong className="text-white">Automate access</strong> — no bots, scrapers, or automated tools interacting with HridAI (API access, if offered, will have separate terms)</li>
            <li className="flex gap-3"><span className="text-red-400">✕</span> <strong className="text-white">Abuse the service</strong> — no attempts to overload, disrupt, or interfere with HridAI's infrastructure</li>
            <li className="flex gap-3"><span className="text-red-400">✕</span> <strong className="text-white">Circumvent limits</strong> — no creating multiple accounts to bypass free tier limits</li>
            <li className="flex gap-3"><span className="text-red-400">✕</span> <strong className="text-white">Use for harm</strong> — no using HridAI to plan, coordinate, or support illegal activity</li>
            <li className="flex gap-3"><span className="text-red-400">✕</span> <strong className="text-white">Impersonate others</strong> — no creating accounts that misrepresent your identity</li>
            <li className="flex gap-3"><span className="text-red-400">✕</span> <strong className="text-white">Share accounts</strong> — your account is for your personal use only</li>
            <li className="flex gap-3"><span className="text-red-400">✕</span> <strong className="text-white">Reverse-engineer</strong> — no attempting to extract HridAI's source code, algorithms, or models</li>
            <li className="flex gap-3"><span className="text-red-400">✕</span> <strong className="text-white">Resell access</strong> — no reselling or redistributing HridAI</li>
          </ul>
          <p className="mt-4 text-white/60 leading-7">
            We reserve the right to suspend or terminate accounts that violate these terms.
          </p>
        </section>

        <hr className="my-10 border-white/10" />

        {/* 7. AI Disclaimers */}
        <section>
          <h2 className="text-2xl font-bold">7. AI Disclaimers</h2>
          <p className="mt-4 text-white/60 leading-7">This is important enough to say again, clearly:</p>

          <h3 className="mt-8 text-xl font-semibold">7.1 Not Professional Advice</h3>
          <p className="mt-4 text-white/60 leading-7">
            HridAI is an AI tool for personal reflection and organization.{" "}
            <strong className="text-white">It is not a substitute for professional advice.</strong> Specifically:
          </p>
          <ul className="mt-3 space-y-3 text-white/60 leading-7">
            <li className="flex gap-3">
              <span className="text-amber-400 font-bold">!</span>
              <span><strong className="text-white">Medical:</strong> HridAI is not a doctor. Do not rely on it for medical diagnoses, treatment decisions, or health advice. If you have a medical concern, see a healthcare provider.</span>
            </li>
            <li className="flex gap-3">
              <span className="text-amber-400 font-bold">!</span>
              <span><strong className="text-white">Mental health:</strong> HridAI is not a therapist or counselor. It may help you organize your thoughts, but it is not therapy. If you're in crisis, contact a mental health professional or crisis helpline.</span>
            </li>
            <li className="flex gap-3">
              <span className="text-amber-400 font-bold">!</span>
              <span><strong className="text-white">Legal:</strong> HridAI is not a lawyer. Do not rely on it for legal advice or interpretation of laws. Consult a qualified attorney for legal matters.</span>
            </li>
            <li className="flex gap-3">
              <span className="text-amber-400 font-bold">!</span>
              <span><strong className="text-white">Financial:</strong> HridAI is not a financial advisor. Do not make investment, tax, or major financial decisions based on HridAI's responses. Consult a qualified financial professional.</span>
            </li>
          </ul>

          <h3 className="mt-8 text-xl font-semibold">7.2 AI Limitations</h3>
          <p className="mt-4 text-white/60 leading-7">
            HridAI uses large language models (LLMs) to process your conversations. These models:
          </p>
          <ul className="mt-3 space-y-2 text-white/60 leading-7">
            <li className="flex gap-3"><span className="text-amber-400">•</span> Can generate incorrect, misleading, or fabricated information</li>
            <li className="flex gap-3"><span className="text-amber-400">•</span> May misunderstand context or nuance</li>
            <li className="flex gap-3"><span className="text-amber-400">•</span> May extract inaccurate information from your conversations</li>
            <li className="flex gap-3"><span className="text-amber-400">•</span> Do not have real-time knowledge of current events</li>
            <li className="flex gap-3"><span className="text-amber-400">•</span> May produce different responses to similar inputs</li>
          </ul>
          <div className="mt-6 rounded-xl border border-amber-400/30 bg-amber-400/5 p-5">
            <p className="text-white/70 leading-7">
              <strong className="text-amber-400">You should review the information HridAI extracts about you</strong>{" "}
              (visible in the Vault UI) and correct any inaccuracies. HridAI is a tool to assist your thinking — not
              an authoritative source of truth about your life.
            </p>
          </div>
        </section>

        <hr className="my-10 border-white/10" />

        {/* 8. Termination */}
        <section>
          <h2 className="text-2xl font-bold">8. Termination</h2>

          <h3 className="mt-8 text-xl font-semibold">8.1 By You</h3>
          <p className="mt-4 text-white/60 leading-7">You can stop using HridAI at any time:</p>
          <ul className="mt-3 space-y-2 text-white/60 leading-7">
            <li className="flex gap-3"><span className="text-emerald-400">•</span> <strong className="text-white">Cancel your subscription</strong> via the app settings. You retain access through the end of your billing period.</li>
            <li className="flex gap-3"><span className="text-emerald-400">•</span> <strong className="text-white">Delete your account</strong> via the app settings. This permanently deletes all your data within 30 days. This action is irreversible.</li>
          </ul>

          <h3 className="mt-8 text-xl font-semibold">8.2 By Us</h3>
          <p className="mt-4 text-white/60 leading-7">We may suspend or terminate your account if:</p>
          <ul className="mt-3 space-y-2 text-white/60 leading-7">
            <li className="flex gap-3"><span className="text-emerald-400">•</span> You violate these Terms (particularly the Acceptable Use section)</li>
            <li className="flex gap-3"><span className="text-emerald-400">•</span> You engage in activity that threatens the security or integrity of the service</li>
            <li className="flex gap-3"><span className="text-emerald-400">•</span> We are required to by law</li>
          </ul>
          <p className="mt-4 text-white/60 leading-7">
            If we terminate your account for a reason other than your violation of these Terms, we will provide
            reasonable notice and an opportunity to export your data.
          </p>
          <p className="mt-4 text-white/60 leading-7">
            If we terminate for Terms violations, we may do so immediately, but will still delete your data within 30
            days of termination.
          </p>

          <h3 className="mt-8 text-xl font-semibold">8.3 Effect of Termination</h3>
          <p className="mt-4 text-white/60 leading-7">Upon termination:</p>
          <ul className="mt-3 space-y-2 text-white/60 leading-7">
            <li className="flex gap-3"><span className="text-emerald-400">•</span> Your access to HridAI ends.</li>
            <li className="flex gap-3"><span className="text-emerald-400">•</span> Your data is permanently deleted within 30 days.</li>
            <li className="flex gap-3"><span className="text-emerald-400">•</span> Any remaining subscription period is forfeit if termination is due to your violation of these Terms.</li>
          </ul>
        </section>

        <hr className="my-10 border-white/10" />

        {/* 9. Limitation of Liability */}
        <section>
          <h2 className="text-2xl font-bold">9. Limitation of Liability</h2>
          <p className="mt-4 text-white/60 leading-7">To the maximum extent permitted by applicable law:</p>
          <ul className="mt-3 space-y-3 text-white/60 leading-7">
            <li className="flex gap-3">
              <span className="text-emerald-400">•</span>
              <span><strong className="text-white">uFactorial provides HridAI "as is" and "as available."</strong> We make no warranties, express or implied, about the reliability, accuracy, or availability of the service.</span>
            </li>
            <li className="flex gap-3">
              <span className="text-emerald-400">•</span>
              <span><strong className="text-white">We are not liable</strong> for any indirect, incidental, special, consequential, or punitive damages arising from your use of HridAI.</span>
            </li>
            <li className="flex gap-3">
              <span className="text-emerald-400">•</span>
              <span><strong className="text-white">Our total liability</strong> for any claim related to HridAI is limited to the amount you paid us in the 12 months preceding the claim, or $100, whichever is greater.</span>
            </li>
            <li className="flex gap-3">
              <span className="text-emerald-400">•</span>
              <span><strong className="text-white">We are not responsible</strong> for decisions you make based on HridAI's responses. See Section 7 (AI Disclaimers).</span>
            </li>
          </ul>
          <p className="mt-4 text-white/60 leading-7">
            These limitations apply to the extent permitted by law. Some jurisdictions do not allow certain limitations,
            in which case the limitation applies to the maximum extent permitted.
          </p>
        </section>

        <hr className="my-10 border-white/10" />

        {/* 10. Indemnification */}
        <section>
          <h2 className="text-2xl font-bold">10. Indemnification</h2>
          <p className="mt-4 text-white/60 leading-7">
            You agree to indemnify and hold uFactorial harmless from any claims, damages, or expenses (including
            reasonable attorney fees) arising from:
          </p>
          <ul className="mt-3 space-y-2 text-white/60 leading-7">
            <li className="flex gap-3"><span className="text-emerald-400">•</span> Your use of HridAI</li>
            <li className="flex gap-3"><span className="text-emerald-400">•</span> Your violation of these Terms</li>
            <li className="flex gap-3"><span className="text-emerald-400">•</span> Your violation of any third party's rights</li>
          </ul>
        </section>

        <hr className="my-10 border-white/10" />

        {/* 11. Dispute Resolution */}
        <section>
          <h2 className="text-2xl font-bold">11. Dispute Resolution</h2>

          <h3 className="mt-8 text-xl font-semibold">11.1 Informal Resolution First</h3>
          <p className="mt-4 text-white/60 leading-7">
            Before filing any formal claim, you agree to contact us at{" "}
            <a href="mailto:legal@ufactorial.com" className="text-emerald-400 hover:underline">legal@ufactorial.com</a>{" "}
            and attempt to resolve the dispute informally for at least 30 days.
          </p>

          <h3 className="mt-8 text-xl font-semibold">11.2 Governing Law</h3>
          <p className="mt-4 text-white/60 leading-7">
            These Terms are governed by the laws of India, without regard to conflict of law principles. You agree to
            submit to the exclusive jurisdiction of the courts located in India for any disputes that cannot be resolved
            informally.
          </p>

          <h3 className="mt-8 text-xl font-semibold">11.3 Class Action Waiver</h3>
          <p className="mt-4 text-white/60 leading-7">
            To the extent permitted by applicable law, you agree to resolve disputes individually and waive any right
            to participate in a class action, class arbitration, or representative proceeding.
          </p>
        </section>

        <hr className="my-10 border-white/10" />

        {/* 12. Changes to These Terms */}
        <section>
          <h2 className="text-2xl font-bold">12. Changes to These Terms</h2>
          <p className="mt-4 text-white/60 leading-7">We may update these Terms from time to time. When we do:</p>
          <ul className="mt-3 space-y-2 text-white/60 leading-7">
            <li className="flex gap-3"><span className="text-emerald-400">•</span> We will update the "Last Updated" date at the top.</li>
            <li className="flex gap-3"><span className="text-emerald-400">•</span> For material changes, we will notify you via <strong className="text-white">email</strong> at least <strong className="text-white">30 days</strong> before the changes take effect.</li>
            <li className="flex gap-3"><span className="text-emerald-400">•</span> If you disagree with the changes, you may cancel your account before the changes take effect.</li>
            <li className="flex gap-3"><span className="text-emerald-400">•</span> Continued use of HridAI after changes take effect constitutes acceptance of the updated Terms.</li>
          </ul>
        </section>

        <hr className="my-10 border-white/10" />

        {/* 13. General Provisions */}
        <section>
          <h2 className="text-2xl font-bold">13. General Provisions</h2>
          <ul className="mt-4 space-y-3 text-white/60 leading-7">
            <li className="flex gap-3">
              <span className="text-emerald-400">•</span>
              <span><strong className="text-white">Entire Agreement:</strong> These Terms, together with our Privacy Policy, constitute the entire agreement between you and uFactorial regarding HridAI.</span>
            </li>
            <li className="flex gap-3">
              <span className="text-emerald-400">•</span>
              <span><strong className="text-white">Severability:</strong> If any provision is found unenforceable, the remaining provisions continue in effect.</span>
            </li>
            <li className="flex gap-3">
              <span className="text-emerald-400">•</span>
              <span><strong className="text-white">No Waiver:</strong> Our failure to enforce any provision does not waive our right to enforce it later.</span>
            </li>
            <li className="flex gap-3">
              <span className="text-emerald-400">•</span>
              <span><strong className="text-white">Assignment:</strong> You may not assign your rights under these Terms. We may assign ours in connection with a merger, acquisition, or sale of assets (with notice to you).</span>
            </li>
            <li className="flex gap-3">
              <span className="text-emerald-400">•</span>
              <span><strong className="text-white">Force Majeure:</strong> We are not liable for failures caused by circumstances beyond our reasonable control.</span>
            </li>
          </ul>
        </section>

        <hr className="my-10 border-white/10" />

        {/* 14. Contact Us */}
        <section>
          <h2 className="text-2xl font-bold">14. Contact Us</h2>
          <ul className="mt-4 space-y-2 text-white/60 leading-7">
            <li className="flex gap-3"><span className="text-emerald-400">•</span> <strong className="text-white">General inquiries:</strong> <a href="mailto:support@ufactorial.com" className="text-emerald-400 hover:underline">support@ufactorial.com</a></li>
            <li className="flex gap-3"><span className="text-emerald-400">•</span> <strong className="text-white">Legal inquiries:</strong> <a href="mailto:legal@ufactorial.com" className="text-emerald-400 hover:underline">legal@ufactorial.com</a></li>
            <li className="flex gap-3"><span className="text-emerald-400">•</span> <strong className="text-white">Privacy inquiries:</strong> <a href="mailto:privacy@ufactorial.com" className="text-emerald-400 hover:underline">privacy@ufactorial.com</a></li>
            <li className="flex gap-3"><span className="text-emerald-400">•</span> <strong className="text-white">Website:</strong> <a href="https://ufactorial.com" className="text-emerald-400 hover:underline">ufactorial.com</a></li>
          </ul>
        </section>

        <hr className="my-10 border-white/10" />

        <p className="text-white/40 text-sm italic leading-7">
          These terms are written to be readable because we believe agreements should be understood, not just signed.
          If you have questions, email us.
        </p>

        {/* Bottom nav */}
        <div className="mt-12 flex flex-col gap-4 sm:flex-row sm:justify-between border-t border-white/10 pt-8">
          <Link to="/" className="text-sm text-white/60 hover:text-white transition">
            Back to HridAI
          </Link>
          <Link to="/privacy" className="text-sm text-white/60 hover:text-white transition">
            Privacy Policy
          </Link>
        </div>
      </Container>
    </div>
  );
}
